ASEMD refactor
zincware/IPSuite pull request #168
Opened 2023-08-02 19:38 UTC by Tetracarbonylnickel

This PR implements a overhaul of the ASEMD Node and a couple of features related to it.

- ASEMD Node
    - steps is now the total number of MD steps
    - sampling_rate is the number that defines after how many MD steps a structure is loaded to the cache
    - progress bar now gives proper it/s
    - progress bar also shows how many fs the md is running
    - init_velocities now zntrack.zn.deps() and velocities_cache zntrack.zn.outs(), with that MD simulations can now be continued within one project
    - constraints now can be set in similar way as the checker and the thermostat
    - metrics is now written every sampling_rate iteration
    - having multiple ThresholdChecker is now possible
    
- FixedShpereMD is now a constraint Node (similar than checker)

- Checker are overhauled

- EMT calculator can now write stress to hdf5 files

- addresses issue #158 #133. In principle also #142 because checker write the relevant metrics into metrics_cache which is zn.plots(). Maybe extra hook for tracking certain metrics during a MD? Is very fast implemented.

2023-08-02 19:40 UTC, Tetracarbonylnickel commented on ipsuite/analysis/model/dynamics_checks.py
>              )
I was not sure with that. Maybe you can give me some input if this is how you intend it.

2023-08-03 06:38 UTC, PythonFZ requested changes
Thanks for the MD fix. This was required and looks much, much better now! Only some small comments and maybe one addition.

2023-08-03 06:38 UTC, PythonFZ commented on ipsuite/analysis/model/dynamics_checks.py
> +        return self.status
Could this be part of the parent class?

2023-08-03 06:38 UTC, PythonFZ commented on ipsuite/analysis/model/dynamics_checks.py
>              )
I guess for non-skalar values we can use the maximum value. Would this also require `if np.max(distance) > self.max_std * std` ?

2023-08-03 06:38 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        saved total energy and metrics from the check nodes
`metrics_dict` might be the wrong name for this data. Maybe we could rename it to `thermo` like in lammps https://docs.lammps.org/thermo.html

2023-08-03 06:38 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        saved total energy and metrics from the check nodes
Could we also introduce `thermo_interval: int` to update this data in a different interval than dumping the atoms.
The reason for this is, that with e.g. 100_000 we have > 200_000 datapoints in the csv file and plotting them can be very slow so we might only want the thermo data every 1000 steps while we dump the trajectories every step?

2023-08-03 06:38 UTC, PythonFZ commented on ipsuite/analysis/model/dynamics_checks.py
> +        return self.status
fixed in 51f5b73

2023-08-03 06:44 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        saved total energy and metrics from the check nodes
To simplify things I'd suggest:
- default for `thermo_interval: int = zn.params(None)` and make ist the same as `sampling_interval`
- only allow `thermo_interval` to be a multiple of `sampling_interval`. We can check that in the `_post_init_`.

2023-08-03 06:44 UTC, Tetracarbonylnickel commented on ipsuite/calculators/ase_md.py
> +        saved total energy and metrics from the check nodes
Isn't it better to have the data and than use every nth datapoint for plotting? Sometimes you may want to zoom in some regions or want to see how smooth the kurve is?

2023-08-03 06:49 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        saved total energy and metrics from the check nodes
Let's leave it as is for now and maybe do that in another PR. Maybe there is also a way to do this on the DVC side.

2023-08-03 08:15 UTC, Tetracarbonylnickel commented on ipsuite/analysis/model/dynamics_checks.py
>              )
Yes you are right and it is implemented now.

2023-08-04 15:33 UTC, merged