213 forces uncertainty selection broken
zincware/IPSuite pull request #215
Opened 2023-10-17 11:02 UTC by Tetracarbonylnickel

This PR fixes the  forces uncertainty selection.
The `ThresholdSelection` now gets a new keyword `dim_reduction` where you can choose how you want do reduce the dimensionallety (`mean` or `max`) and along which axes you want to reduce the uncertainty. With that it is also more flexible for future uncertainty measures.

2023-10-23 07:30 UTC, PythonFZ requested changes
Looks good! I have a few comments to be addressed before merging.

2023-10-23 07:30 UTC, PythonFZ commented on ipsuite/configuration_selection/threshold.py
> +    save_fig = zntrack.params(True)
I think we can use `save_fig = True` all the time. The figures are pngs, so they are quite small and there shouldn't be any downside in saving them. Also, I think the Node may fail, if `save_fig = False` because the `img_selection` `outs_path` is missing.

2023-10-23 07:30 UTC, PythonFZ commented on ipsuite/configuration_selection/threshold.py
> +        by calculating either the maximum or mean value.
Can  you add the available keys here, either by highlighting them via
> the "maximum" or "mean" value

or by providing another sentence:

> choose from ["maximum", "mean"]

afterwards

2023-10-23 07:30 UTC, PythonFZ commented on ipsuite/configuration_selection/threshold.py
> +    dim_reduction: str = zntrack.params("None")
Can the default just be `None`, which would be `null` in json?

2023-10-23 07:30 UTC, PythonFZ commented on ipsuite/configuration_selection/threshold.py
> +        }
I think this could be moved outside the `select_atoms` method and then be `REDUCTIONS = {}`.
I'd also prefer to not include the type information in the variable name (common anti-pattern in Python. I have done this a lot as well, but we should avoid it.)

2023-10-23 07:30 UTC, PythonFZ commented on ipsuite/configuration_selection/threshold.py
> +                reference = np.max(reference, axis=self.reduction_axis)
Shouldn't this also use the `REDUCTION` function?

2023-10-23 07:30 UTC, PythonFZ commented on tests/unit_tests/configuration_selection/test_threshold.py
> +    if "forces_uncertainty" in key and "None" in dim_reduction:
I know these are strings, but I think it would be better to check for equality than `in` using 

`if key == "forces_uncertainty" and dim_reduction is None:`

2023-10-23 08:29 UTC, Tetracarbonylnickel commented on ipsuite/configuration_selection/threshold.py
> +                reference = np.max(reference, axis=self.reduction_axis)
Shouldn't the mean force of the System equal to zero? So I think using only the max forces is the best option here.

2023-10-24 19:44 UTC, Tetracarbonylnickel commented
I included all your comments. I also had to finde some abstractions because there where to many if statements in the function.

2023-10-25 07:08 UTC, PythonFZ commented on ipsuite/configuration_selection/threshold.py
> +        Choose from ["max", "min"]
Should be `["max", "mean"]`

2023-10-25 07:12 UTC, PythonFZ requested changes
Small comment, if this one is resolved we can merge.

2023-10-25 07:12 UTC, PythonFZ commented on ipsuite/configuration_selection/threshold.py
> +    ) -> typing.List[int]:
Are you planning on using this function with `safe_fig = False` in the future? If not, I'd suggest removing the argument entirely and always save the figure.

Also typo: `safe_fig` should be `save_fig`.

2023-10-25 09:18 UTC, PythonFZ approved these changes

2023-11-03 13:20 UTC, merged