MixCalculator
zincware/IPSuite pull request #255
Opened 2024-01-04 16:59 UTC by PythonFZ

2024-01-09 15:36 UTC, M-R-Schaefer commented on ipsuite/calculators/mix.py
> +def _update_is_exists(results, key, atoms_list, func, mean: bool):
`update_if_exists`?

2024-01-09 15:38 UTC, M-R-Schaefer requested changes
possible minor spelling mistake

2024-01-11 17:56 UTC, PythonFZ commented on ipsuite/calculators/mix.py
> +        )
What do you think about the changes? If you have an idea, please show me how to make it look better.

2024-01-11 19:01 UTC, PythonFZ commented on ipsuite/calculators/mix.py
> +        )
had to rollback, ideas was https://github.com/zincware/IPSuite/pull/255/commits/bed696a9a4597abafc49736de487f7f94f027df7

2024-01-19 13:04 UTC, merged