Docs
zincware/IPSuite pull request #264
Opened 2024-02-28 15:00 UTC by MrJulEnergy

Add basic docs to IPS

2024-02-28 15:27 UTC, MrJulEnergy commented on pytest_log.txt
> +UNEXPECTED EXCEPTION: DVCProcessError('DVC CLI failed (253) for cmd: \n "dvc stage add --name SmilesToConformers --force --outs nodes/SmilesToConformers/atoms.h5 --params params.yaml:SmilesToConforme
What is going on here?

2024-02-28 15:28 UTC, MrJulEnergy commented on ipsuite/configuration_generation/packmol.py
> +    ...     water = ips.configuration_generation.SmilesToConformers(
It is important to note, that indentations should be done with `...` instead of `>>>`

2024-02-29 07:22 UTC, PythonFZ requested changes
Very nice job!
There are some small comments that should be addressed as well as removing `pytest_log.txt`.

It would be great, if you could incorporate the old docs, including the example notebooks. Then we have a clean PR and don't have the `old_docs` branch in `main`.

2024-02-29 07:22 UTC, PythonFZ commented on docs/notes.txt
> +    """Add two nums
remove file?

2024-02-29 07:22 UTC, PythonFZ commented on docs/source/_get_started/ips.rst
> +Each modlule (kown in the IPS environment as Node), takes some inputs and provieds outputs. These outputs can then be redirected to other Nodes.
Nodes are not `modules`, e.g. `ips.configuration_selection` is a `module`. They are more `classes` or just: IPSuite partitions these workflows into so called nodes, each dedicated for one specific task.

2024-02-29 07:22 UTC, PythonFZ commented on docs/source/_get_started/ips.rst
> +IPSuite already provides various Nodes in order to meet the needs of MPL creation and training.
remove `already`

2024-02-29 07:22 UTC, PythonFZ commented on docs/source/_get_started/quickstart.rst
> +    poetry install .
remove `.`

2024-02-29 07:22 UTC, PythonFZ commented on docs/source/_get_started/quickstart.rst
> +To get to know the IPS procedures we will do an example problem.
this is now duplicated, maybe mention the two installation pathways first and then how to create a project. One sentence that a dedicated folder is required, because each IPS project lives in a GIT repo.

2024-02-29 07:22 UTC, PythonFZ commented on docs/source/_get_started/quickstart.rst
> +The goal is to place water molecules inside a box at a specified density.
You should mention, that `SmilesToAtoms` uses https://github.com/rdkit/rdkit

2024-02-29 07:22 UTC, PythonFZ commented on docs/source/_get_started/quickstart.rst
> +These parameters files, namely `params.yaml` can be viewed and parameters can be changed without rerunning the python script.
maybe add the mermaid graph, `These parameter files`

2024-02-29 07:22 UTC, PythonFZ commented on docs/source/_get_started/quickstart.rst
> +the nodes are executed, which results in the generation of firstly a single water molecule by the SmilesToAtoms node and then the placement
the workflow consiting of thede nodes is executed

2024-02-29 07:22 UTC, PythonFZ commented on ipsuite/calculators/ase_geoopt.py
> +    init_kwargs: dict = zntrack.zn.params({})
I assume this is from @M-R-Schaefer ?

2024-02-29 07:22 UTC, PythonFZ commented on ipsuite/calculators/lammps.py
> +    2
remove

2024-02-29 07:22 UTC, PythonFZ commented on ipsuite/configuration_generation/packmol.py
> +        >>> a = subprocess.run(["dvc", "init"])
Could we make this a `ips.utils` function like https://github.com/zincware/ZnTrack/blob/a85bd375832cf7e3b7980dc5f9fa452e2fcbd40f/zntrack/utils/__init__.py#L190-L219 but with less boilder plate code, just ge temp path and git / dvc init.

the cleanup should then use `tmp_path.cleanup()`

2024-02-29 07:22 UTC, PythonFZ commented on old_docs/source/_examples/index.rst
> +Later notebooks feature some more complex workflows which are closer to real world use case.
integrate into new docs

2024-02-29 08:49 UTC, MrJulEnergy commented on ipsuite/calculators/ase_geoopt.py
> +    init_kwargs: dict = zntrack.zn.params({})
Yes

2024-02-29 14:06 UTC, PythonFZ commented on ipsuite/utils/docs.py
> +    # Generate a temp directory and initalize dvc and git in it (also delete it up after that)
use docstring

2024-03-06 21:34 UTC, PythonFZ commented
I found the following when running `make html`: `WARNING: html_static_path entry '_static' does not exist`

2024-04-15 12:04 UTC, PythonFZ approved these changes
Looks good!

2024-04-16 07:29 UTC, merged