Add a Bond Length Constraint Node
zincware/IPSuite pull request #294
Opened 2024-05-06 08:19 UTC by MrJulEnergy

2024-05-06 12:50 UTC, PythonFZ requested changes
Looks good. To be merged this needs:
- [ ] update in `changelod.md`
- [ ] tests
- [x] pre-commit.ci fixes

2024-05-08 11:27 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +    atom_id = zntrack.params()
should probably be `ids` or `atom_ids` as this is not a single `atom_id` but a list of such.

2024-05-08 11:28 UTC, PythonFZ commented on tests/integration/calculators/test_ase_md.py
> +
Can you add a test for Hook as well?

2025-02-16 10:56 UTC, MrJulEnergy commented
I believe only a test for `HookeanConstraint` is mission bevore merging. However I'm not sure how to construct a test for this

2025-04-03 09:48 UTC, MrJulEnergy commented
There seem to be larger problem with the two nodes which needs to be investigated firstly

2025-04-04 16:50 UTC, merged