Mapped ase md and Flatten node
zincware/IPSuite pull request #299
Opened 2024-05-16 20:57 UTC by Tetracarbonylnickel

2024-05-21 13:05 UTC, Tetracarbonylnickel commented
So far the implementation is ready and tested. Will get an overhaul as soon as it is possible to safe more than one trajectory in h5 in a structured way.

2024-05-21 14:55 UTC, PythonFZ requested changes
I think this will be a great addition but I have some comments.
Something I'm undecided is the split into `data_id` and `data_ids` parameters.
We could easily unify them into `data_ids: list[int]` and if `run` we mandate that `len(data_ids) == 1` ? But on the other hand, using different names makes it more clear what is goind on.

2024-05-21 14:55 UTC, PythonFZ commented on ipsuite/base/base.py
> +        self.atoms = atoms
I think this could be one line, but I don't mind.

2024-05-21 14:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        with a given 'data_id'.
I think `data` should always be `list[atoms]` afaik, there is no Node in IPS that produces a `ase.Atoms`, they are always lists?

2024-05-21 14:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +                atoms = list(ase.io.iread(self.data_file))
This is dangerous, where is this required?

2024-05-21 14:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        self.db.initialize_database_groups()
Code duplication with `map`

2024-05-22 06:50 UTC, Tetracarbonylnickel commented on ipsuite/calculators/ase_md.py
> +                atoms = list(ase.io.iread(self.data_file))
That is a good point. Actually I modified the ProcessAtoms base class which also uses that line, and have to admit that I don't know if it is needed. Maybe we can talk about the atoms and file handling so I can adjust this in the base class too?

2024-05-22 08:11 UTC, Tetracarbonylnickel commented on ipsuite/calculators/ase_md.py
> +                atoms = list(ase.io.iread(self.data_file))
Should be address this in a separate PR?

2024-06-24 09:37 UTC, Tetracarbonylnickel commented
Also solves issue #301

2024-06-26 11:32 UTC, PythonFZ approved these changes
Great addition, LGTM 👍

2024-06-26 11:32 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        modifies temperature or cell during the simulation.
This can in principle be anything, not just temperature or cell. Why did you decide to remove the base-class type hint?

2024-06-26 12:32 UTC, merged