Gromacs Node
zincware/IPSuite pull request #306
Opened 2024-07-12 12:46 UTC by PythonFZ

This PR implements a Node for classical sampling of configurations using https://github.com/alanwilter/acpype and the GAFF as well as PACKMOL and RDKit for generating boxes from smiles.

--- 
I've added some trajectory conversion utilities. The energy reading code works in principle but I am fairly certain that the energies I obtain are wrong in some way. There is also an issue that the gmx energy command works on the CLI but not from within the node so I have opted to set the energies to 0 for now.
---

# TODO
- [x] remove `maxwarn`, currently identifiers don't seem to be unique
- [x] box size
- [x] packmol pbc issue
- [ ] make energy / force saving to ASE atoms optional
- [ ] configure gromacs mpi/omp parameters for better performance
- [ ] clean up files? When converting to ASE we have a large duplication w.r.t to the gromacs output files. Do we want to keep them?
- [ ] correct time step in h5md
- [ ] gf2bf (yaml to gromacs) parser

2024-07-12 13:01 UTC, M-R-Schaefer commented on ipsuite/configuration_generation/gmx.py
> +            "1",
the supercell is already in the self.box file right? is it correct to then use -d 1? does that not lower the density?

2024-07-12 13:03 UTC, M-R-Schaefer commented on ipsuite/configuration_generation/gmx.py
> +                "10",
maxwarn 10 seems a bit excessive. Has this been an issue in the IL tests so far?

2024-07-12 13:04 UTC, M-R-Schaefer requested changes
some questions on the hardcoded gmx parameters. Otherwise it looks good.

2024-07-12 13:09 UTC, PythonFZ commented on ipsuite/configuration_generation/gmx.py
> +            "1",
No, it is not - I'm still struggling with the correct box size

2024-07-12 13:10 UTC, M-R-Schaefer commented on ipsuite/configuration_generation/gmx.py
> +class Smiles2Gromacs(base.IPSNode):
Perhaps a different name would be more informative. To me Smiles2Gromacs sounds like it creates gromacs input files but it also runs simulations.

2024-07-12 13:12 UTC, M-R-Schaefer commented on ipsuite/configuration_generation/gmx.py
> +            "1",
hm curious. What is the issue? If packmol can create a box with a correct density, then it should be fine to set -d 0, right? Alternatively, the node can run arbitrary mdp files, we can just add an NPT equilibration step and maybe add a warning about this in the docstring.

2024-07-12 15:41 UTC, M-R-Schaefer commented on ipsuite/configuration_generation/gmx.py
> +class Smiles2Gromacs(base.IPSNode):
Smiles2GromacsRun?

2024-07-12 15:46 UTC, M-R-Schaefer commented on ipsuite/configuration_generation/gmx.py
> +            subprocess.run(cmd, check=True, cwd=self.output_dir)
is this correctly using the final configuration of one run as the starting configuration of the next?

2024-07-12 15:47 UTC, M-R-Schaefer requested changes
minor clarification

2024-07-12 15:51 UTC, M-R-Schaefer commented on ipsuite/configuration_generation/gmx.py
> +            subprocess.run(cmd, check=True, cwd=self.output_dir)
There is currently no conversion to ASE atoms right?

2024-07-22 06:18 UTC, PythonFZ commented on ipsuite/configuration_generation/gmx.py
> +            subprocess.run(cmd, check=True, cwd=self.output_dir)
https://github.com/zincware/IPSuite/pull/308

2024-07-25 06:31 UTC, PythonFZ commented
gf2bf

2024-07-26 09:12 UTC, M-R-Schaefer approved these changes

2024-07-26 09:21 UTC, PythonFZ commented on ipsuite/configuration_generation/gmx.py
> +class Smiles2Gromacs(base.IPSNode):
I think the name is fine - it generates the gromacs input files and once you define the node you need to give the mdp files which clarifies that it is also executing a gromacs run. I don't think we will ever add a Node that only creates the gromacs input files without running them.

2024-07-26 09:29 UTC, merged