Intermolecular forces uncertainty quantification
zincware/IPSuite pull request #346
Opened 2024-11-26 08:08 UTC by M-R-Schaefer

Adds node which performs the uncertainty decomp for force uncertainties. This is achieved by performing the force decomposition for each ensemble member's forces and taking the std of the resulting ensemble rot/trans/vib forces.

2024-11-29 10:50 UTC, M-R-Schaefer commented
Examples are also still failing on main

2024-11-30 09:59 UTC, PythonFZ requested changes
Great addition. Some small comments.

2024-11-30 09:59 UTC, PythonFZ commented on ipsuite/analysis/model/math.py
> +        mu = (masses / mol_mas)[:, None, None]
else: raise ValueError or KeyError

2024-11-30 09:59 UTC, PythonFZ commented on ipsuite/analysis/model/math.py
> +    # TODO fix for n=2
remove

2024-11-30 09:59 UTC, PythonFZ commented on ipsuite/analysis/model/math.py
> +        result = np.cross(mi_ri, Iinv_fxr)
might be better to use else if key == forces else raise, if someone passes idk, `ensemble_force` by accident, this would raise an error instead of silently ignore it.

2024-11-30 09:59 UTC, PythonFZ commented on ipsuite/analysis/model/math.py
> +    true = true[mask]
I don't like `true` as a variable name, to you think it would be possible to use something else?

2024-11-30 09:59 UTC, PythonFZ commented on ipsuite/analysis/model/predict.py
> +        # TODO update plots true - pred y axis
todo?

2024-11-30 09:59 UTC, PythonFZ commented on ipsuite/analysis/model/predict.py
> +            #     result = decompose_force_uncertainty(self.x[i], self.y[i])
remove?

2024-11-30 16:52 UTC, M-R-Schaefer commented on ipsuite/analysis/model/predict.py
> +        # TODO update plots true - pred y axis
already done

2024-12-03 09:51 UTC, merged