Generic MD
zincware/IPSuite pull request #43
Opened 2023-04-05 11:07 UTC by Tetracarbonylnickel

This PR introduces some changes to the ASEMD node.
With these changes the node is able to accept different calculator (ase as well as model.calc), different ase dynamic functions and checker nodes. It outputs the velocities of the last structure if a MD should be restarted. Metrics that are tracked with the checker nodes will also appear in the progress bar.

2023-04-05 17:46 UTC, PythonFZ commented on tests/integration/calculators/test_ase_md.py
>          model = ips.models.GAP(data=data.atoms)
We should use the following `env.yaml` here:

```yaml
MLModel:
   OPENBLAS_NUM_THREADS: "1"

ASEMD:
   OPENBLAS_NUM_THREADS: "1"
```

You can set ```GAP(OPENBLAS_NUM_THREADS="1")``` but that will only affect the training and not the usage of the `GAP.calc`. I don't think I can make this work automatically. 

Possible suggestions:

```ASEMD(env={"OPENBLAS_NUM_THREADS": "1"})```
or
```proj.run(env={"OPENBLAS_NUM_THREADS": "1"})``` which would set these for every Node.

Both aren't possible at the moment but I think both could be feasible solutions. What do you think?

2023-04-05 17:49 UTC, PythonFZ commented on tests/integration/calculators/test_ase_md.py
>          model = ips.models.GAP(data=data.atoms)
I made an issue https://github.com/zincware/ZnTrack/issues/573

2023-04-06 09:49 UTC, Tetracarbonylnickel commented on tests/integration/calculators/test_ase_md.py
>          model = ips.models.GAP(data=data.atoms)
I think it is better to set it for every Node. Not sure when it is useful to set it explicitly for one Node.

2023-04-14 12:55 UTC, PythonFZ requested changes

2023-04-14 12:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        return None
Could we use https://github.com/zincware/IPSuite/blob/e9609887cb685e31a6c91bacae898b91740c245a/ipsuite/base/base.py#L172

2023-04-14 12:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        self.temperature = ekin / (1.5 * units.kB)
please use https://github.com/zincware/IPSuite/blob/e9609887cb685e31a6c91bacae898b91740c245a/ipsuite/utils/ase_sim.py#L11

2023-04-14 12:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +    thermostat = zntrack.zn.nodes()
these should be type hinted with `list`

2023-04-14 12:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +
This check should probably be in `_post_init_`

2023-04-14 12:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        _ = get_energy(atoms)
please use https://github.com/zincware/IPSuite/blob/e9609887cb685e31a6c91bacae898b91740c245a/ipsuite/utils/ase_sim.py#L11

2023-04-14 12:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +                    atoms_cache.append(atoms.copy())
Please use https://github.com/zincware/IPSuite/blob/e9609887cb685e31a6c91bacae898b91740c245a/ipsuite/utils/ase_sim.py#L42

2023-04-14 12:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +                                step=1,
`step` is probably `self.sampling_rate`

2023-04-14 12:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
> +        if not any(stop):
I think we want to save indenpently of `stop`. The last configurations might be the most interesting one e.g. for single point calculations.

2023-04-14 12:55 UTC, PythonFZ commented on ipsuite/calculators/ase_md.py
>  class FixedSphereASEMD(ASEMD):
How would `FixedSphereASEMD` be affected by these changes? Would it be possible to make the `FixedSphere` a `constraints: list = zn.nodes` that one could pass to the `ASEMD` calculator?

2023-04-14 12:56 UTC, PythonFZ commented
Are we interested in saving the velocities for every step? Might be interesting for some analysis methods.

2023-04-14 15:54 UTC, Tetracarbonylnickel commented on ipsuite/calculators/ase_md.py
> +                                step=1,
I am not sure. That is  a part of the old MD node.

2023-04-14 16:56 UTC, Tetracarbonylnickel commented
> Are we interested in saving the velocities for every step? Might be interesting for some analysis methods.

Yes therefor i would introduce another `CheckNode`. Here i just wanted to save the last velocity to be able to continue MD simulations.

2023-04-14 17:00 UTC, Tetracarbonylnickel commented
> > Are we interested in saving the velocities for every step? Might be interesting for some analysis methods.
> 
> Yes therefor i would introduce another `CheckNode`. Here i just wanted to save the last velocity to be able to continue MD simulations.

Isn't the velocity stored in the .h5 file? Because it is available in the `ase.Atoms` Object.

2023-04-14 17:14 UTC, Tetracarbonylnickel commented on ipsuite/calculators/ase_md.py
>  class FixedSphereASEMD(ASEMD):
At the moment it should work as before with all the new functions available. I see no problem in passing it to the `ASEMD` node. It would just need the atoms as `zntrack.zn.deps()`.

2023-04-17 08:08 UTC, PythonFZ commented on tests/integration/calculators/test_ase_md.py
> +        model = ips.models.GAP(data=data.atoms, OPENBLAS_NUM_THREADS="1")
The `` is important for the ASEMD and not so much for the training. Can you pass it to the run instead.
```python
project.run(environment={"OPENBLAS_NUM_THREADS": "1"})
```

2023-04-17 08:08 UTC, PythonFZ approved these changes
Looks good, please address the last comments and if the checks pass we can merge it.

2023-04-17 08:10 UTC, PythonFZ commented
> > > Are we interested in saving the velocities for every step? Might be interesting for some analysis methods.
> > 
> > 
> > Yes therefor i would introduce another `CheckNode`. Here i just wanted to save the last velocity to be able to continue MD simulations.
> 
> Isn't the velocity stored in the .h5 file? Because it is available in the `ase.Atoms` Object.

It is part of the `Atoms` and not part of the `calculator.results` but I'll add it https://github.com/zincware/ZnH5MD/issues/52

2023-04-18 10:29 UTC, merged