Add Standard Deviation Check
zincware/IPSuite pull request #91
Opened 2023-04-26 08:05 UTC by PythonFZ

2023-04-28 09:53 UTC, Tetracarbonylnickel commented on ipsuite/analysis/model/dynamics_checks.py
> +        )
Should this always return the termination message? Then I will change this in the other check nodes.

2023-04-28 09:57 UTC, PythonFZ commented on ipsuite/analysis/model/dynamics_checks.py
> +        )
I think it should be the other way. `__str__` should show description and we add a function for the termination message?

2023-04-28 10:14 UTC, Tetracarbonylnickel commented on ipsuite/analysis/model/dynamics_checks.py
> +        )
Yes sounds good so something like 
```
def __str__(self):
    return f"{self.value}: {self.values[-1]:.3f} K"

def termination_description(self):
   return (
        f"StandardDeviationCheck for '{self.value}' triggered by"
        f" '{self.values[-1]:.3f}' for '{np.mean(self.values):.3f} +-"
        f" {np.std(self.values):.3f}' and max value '{self.max_value}'"
    )
```?
Then I would also adapt the `ASEMD` node to that.

2023-05-02 15:06 UTC, M-R-Schaefer commented on ipsuite/analysis/model/dynamics_checks.py
> +        Maximum value of the property to check before the simulation is stopped
I think this capability could be added to the description of the node. The name of this class is also not quite accurate in my opinion since the maximum value criterion does not interact with the computed standard deviation in any way. Perhaps `ThresholdCheck` would be a suitable alternative name?

2023-05-02 15:07 UTC, M-R-Schaefer requested changes
I feel like the node name and description don't make the ability to check absolute thresholds clear enough.

2023-05-03 14:08 UTC, M-R-Schaefer approved these changes

2023-05-03 14:12 UTC, merged